# -*- ruby -*- ft=ruby
Vagrant.configure('2') do |config|

  # config.omnibus.chef_version = :latest

  config.vm.define "pgsql84" do |pgsql84|
    pgsql84.vm.box = 'centos65-minimal'
    pgsql84.vm.box = 'https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box'
    pgsql84.vm.provision "shell" do |s|
      s.path = 'provision.sh'
      s.args = '8.4'
    end      
  end

  config.vm.define "pgsql93" do |pgsql93|
    pgsql93.vm.box = 'centos65-minimal'
    pgsql93.vm.box = 'https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box'
    pgsql93.vm.provision "shell" do |s|
      s.path = 'provision.sh'
      s.args = '9.3'
    end
  end
end
