# -*- ruby -*- ft=ruby
Vagrant.configure('2') do |config|

  $yum_script =  <<SCRIPT
echo Provisioning emacs...
sudo yum -y install emacs

curl --remote-name -L http://yum.postgresql.org/8.4/redhat/rhel-6-x86_64/pgdg-centos-8.4-3.noarch.rpm
sudo rpm -i pgdg-centos-8.4-3.noarch.rpm

sudo yum -y install postgresql-libs-8.4.20-1.el6_5.x86_64 \
  postgresql84-8.4.21-1PGDG.rhel6.x86_64 \
  postgresql84-devel-8.4.21-1PGDG.rhel6.x86_64 \
  postgresql84-libs-8.4.21-1PGDG.rhel6.x86_64 \
  postgresql84-contrib-8.4.21-1PGDG.rhel6.x86_64 \
  postgresql84-server-8.4.21-1PGDG.rhel6.x86_64
SCRIPT

  # config.omnibus.chef_version = :latest

  config.vm.define "pgsql84" do |pgsql84|
    pgsql84.vm.box = 'centos65-minimal'
    pgsql84.vm.box = 'https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box'
    # pgsql84.vm.provision :chef_solo do |chef|
    #   chef.add_recipe 'postgresql::server'
    #   chef.json = {
    #     'postgresql' => {
    #       'version' => '8.4',
    #       'password' => {
    #         'postgres' => '1234'
    #       },
    #     },
    #   }
    # end
    pgsql84.vm.provision "shell", inline: $yum_script
  end

  config.vm.define "pgsql93" do |pgsql93|
    pgsql93.vm.box = 'centos65-minimal'
    pgsql93.vm.box = 'https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box'
    pgsql93.vm.provision :chef_solo do |chef|
      chef.add_recipe 'postgresql::server'
      chef.json = {
        'postgresql' => {
          'version' => '9.3',
          'password' => {
            'postgres' => '1234'
          },
          'enable_pgdg_yum' => true,
          "client" => {
            "packages" => [ "postgresql93-devel" ]
          },
          'server' => {
            'packages' => [ 'postgresql93-server', 'postgresql93-contrib'],
            'service' => 'postgresql-9.3',
            'service_name' => 'postgresql-9.3'
          },
        },
      }
    end
    pgsql93.vm.provision "shell", inline: $yum_script
  end  
end
