(defun shuffle-lines-buffer ()
  "Shuffle the lines of the current buffer."
  (interactive)
  (setq lines (line-number-at-pos (point-max)))
  ;; (princ "lines ") (print lines)
  (setq transpositions lines)
  (while (and (> lines 1) (> transpositions 0))
    (setq transpositions (- transpositions 1))
    (setq prev (goto-line (random lines)))
    (beginning-of-line)
    (setq start1 (point))
    (end-of-line)
    (setq end1 (point))
    (setq curr (goto-line (random lines)))
    ;; (princ "transpositions ") (print transpositions)
    ;; (princ "prev ") (print prev)
    ;; (princ "start1 ") (print start1)

    ;; (princ "curr ") (print curr)
    (while (= prev curr)
      (setq curr (goto-line (random lines))))
    (beginning-of-line)
    (setq start2 (point))
    (end-of-line)
    (setq end2 (point))
    (transpose-regions start1 end1 start2 end2)))
